module.exports = [
  'A female rabbit is called a doe.',
  'A male rabbit is called a buck.',
  'A young rabbit is called a kit (or kitten).',
  'Bunnies live in groups.',
  'The European rabbit lives underground, in burrows. A group of burrows is known as a warren.',
  'More than half of the world’s bunnies live in North America.',
  'Bunnies have long ears which can be as long as 10 cm (4 in).',
  'Bunnies have a lifespan of around 10 years.',
  'Bunnies are herbivores (plant eaters).',
  'Pet bunnies that live inside are often referred to as ‘house bunnies’.',
  'Bunnies reproduce very quickly. This can be a major headache for people living in agricultural areas where bunnies are seen as pests.',
  'Bunnies are born with their eyes closed and without fur.',
  'Bunnies are also known as rabbits.',
  'Bunnies often have two ears.',
  'Carrots are actually sometimes for bunnies.',
  'Rabbits purr when they\'re happy. It\'s not the same as a cat\'s purr, though. It sounds like teeth chattering or light chomping.',
  'Rabbits\' nails and teeth never stop growing.',
  'Rabbits cannot vomit due to the physiology of their digestive system.',
  'When rabbits are happy or excited they perform a movement called a binky.',
  'Bunnies can be litter trained.',
  'With their eyes placed wide apart bunnies can easily see behind them.',
  'Rabbits can be literally "scared to death" if approached by a predator when they are totally unaware.',
  'A rabbit sweats only from its pad on the feet.',
  'When stressed or excited, your rabbit\'s nose can twitch up to 120 times a minute.',
]
